# This is a basic workflow to help you get started with Actions

name: Render OpenAPI Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      
      # Get the "content" key from the API spec
      - name: Read yaml
        id: read-openapi-yaml
        uses: jbutcher5/read-yaml@1.6
        with:
          file: './.insomnia/ApiSpec/spc_0c4342d7a97340279786357ac32d85dd.yml'
          key-path: '["contents"]'

      # Save content as openapi.yml
      - name: Save openapi.yml
        run: mkdir docs; echo '${{ steps.read-openapi-yaml.outputs.data }}' > ./docs/openapi.yaml

      # Render openapi.yml to HTML with Redoc
      - name: Render HTML Docs
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle openapi.yaml --output ./docs/index.html'

      # Commit changes
      - name: Commit & Push
        uses: actions-js/push@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}